### ISSUE TITLE
Crash with empty call log

### ISSUE THREAD

**Issue by artemkaxboy** [artemkaxboy/autoredial-ce#24]
**Describe the bug**
The app crashes when the call log is empty

**To Reproduce**
Use redial last with empty call log.

**Stacktrace**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter number
        at com.artemkaxboy.android.autoredialce.Redialing.start(Redialing.kt)
        at com.artemkaxboy.android.autoredialce.ReceiverCommand$1.onPostExecute(ReceiverCommand.java:44)
        at com.artemkaxboy.android.autoredialce.ReceiverCommand$1.onPostExecute(ReceiverCommand.java:41)
```

**Comment by artemkaxboy** [comment]
A null-check added
